project:
  type: website
  preview:
    browser: false
    host: 0.0.0.0
    port: 4200

website:
  title: "Mat's Blog"
  site-url: https://blog.matdmiller.com
  open-graph: true
  twitter-card: true
  google-analytics: "G-JPDLB55959"
  navbar:
    left:
      - href: https://matdmiller.com
        text: Home
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/matdmiller
      - icon: twitter
        href: https://twitter.com/matdmiller
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: lux
      dark: lux
#    css: styles.css

execute:
  freeze: auto

editor:
  render-on-save: true
